spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/todo}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${SPRING_DATASOURCE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true