name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Copy JAR
        run: cp target/todo-0.0.1-SNAPSHOT.jar ~/todo-0.0.1-SNAPSHOT.jar

      - name: Restart Service
        run: sudo systemctl restart todo